Add userIdBlacklist option
rciam/proxystatistics-simplesamlphp-module pull request #12
Opened 2021-02-04 18:05 UTC by lionick

2021-02-05 12:31 UTC, NicolasLiampotis requested changes

2021-02-05 12:31 UTC, NicolasLiampotis commented on lib/Auth/Process/statistics.php
> +            SimpleSAML_Logger::debug("[proxystatistics:proccess] Skipping blacklisted user with id " . var_export($request['Attributes'][$this->config->getString('userIdAttribute')], true));
debug --> notice

2021-02-07 09:13 UTC, lionick commented on lib/Auth/Process/statistics.php
> +            SimpleSAML_Logger::debug("[proxystatistics:proccess] Skipping blacklisted user with id " . var_export($request['Attributes'][$this->config->getString('userIdAttribute')], true));
done

2021-02-08 09:37 UTC, NicolasLiampotis approved these changes
LGTM

2021-02-08 09:37 UTC, merged